### ISSUE TITLE
Logo and stickers

### ISSUE THREAD

**Issue by kristjanmik** [apis-is/apis#159]
We need to decide on the logo that we want to use. When the logo has been confirmed we can start printing stickers!

**Comment by koddsson** [comment]
@benediktvaldez You had some initial mockups and ideas?

**Comment by benediktvaldez** [comment]
@koddsson yup - will post a few mocksups

**Comment by koddsson** [comment]
I'm excited!

![](http://replygif.net/i/500.gif)

**Comment by koddsson** [comment]
Oh dude! Logo idea!

>Powered by apis.is

That be awesome for people to put on their apps that they build with apis.is! Something like this (but more awesome):

![](http://www.paradyne.com.au/wp-content/uploads/2013/09/Powered-by-Windows-azure-logo-e1383867363836-960x144.png)

**Comment by benediktvaldez** [comment]
Assigning this to myself so I won't keep forgetting!

(coming soon)

![](http://www.gifbin.com/bin/082011/1314959189_george_clooney__soon.gif)

**Comment by benediktvaldez** [comment]
For reference, this is roughly the outcome of tonights working session. We'll see how it goes

http://drop.bdvs.info/11i9P

**Comment by koddsson** [comment]
I want "Powered by APIs.is" on my laptop!

**Comment by koddsson** [comment]
![](http://cdn3.gurl.com/wp-content/uploads/2013/06/waiting.gif)

@benediktvaldez
