### ISSUE TITLE
Create docs.beta.apis.is

### ISSUE THREAD

**Issue by benediktvaldez** [apis-is/apis#182]
`gulp clean --prod && gulp build --prod`

builds stuff into ./dist/

**Comment by benediktvaldez** [comment]
@kristjanmik this is ready to go on `v2-docs` branch, except one command missing above..

So to get a production ready build running, you need to have `gulp` and `requirejs` globally installed via npm, and run the following

```shell
gulp clean --prod
gulp build --prod
r.js -o build-require.js
```

**Comment by benediktvaldez** [comment]
@kristjanmik  It's running here now

https://github.com/apis-is/docs/tree/gh-pages

**Comment by kristjanmik** [comment]
Done
