### ISSUE TITLE
Explicitly specify utf8 charset

### ISSUE THREAD

**Issue by eirikurn** [apis-is/apis#197]
When opening an api in Chrome's JSONView, it messes up icelandic characters:

![messed up utf8](http://cl.ly/image/1u2B0p2v390s/Image%202015-03-03%20at%203.16.37%20pm.png)

While they look fine in other viewers. Hopefully, setting a more explicit content-type will fix the issue:

```
Current:
Content-Type: application/json

Should be?
Content-Type: application/json; charset=utf-8
```

If not, then the problem might be some latin1/utf8 mess, i.e. the content may be scraped from non-utf8 sources, in which case it somehow needs to be properly converted into utf8.

**Comment by benediktvaldez** [comment]
I get the same result in Safari so I don't think it's chrome specific

**Comment by koddsson** [comment]
I don't get it :<

![screen shot 2015-03-03 at 07 42 42](https://cloud.githubusercontent.com/assets/318208/6465898/d940131c-c178-11e4-8885-54a719e27990.png)

What's the path to the endpoint that you are calling?

**Comment by eirikurn** [comment]
http://apis.is/company?name=alm

It could be fallbacking to some default OS/browser charset.

**Comment by benediktvaldez** [comment]
Yup looks like it @eirikurn , when I go into View > Text Encoding and select UTF-8 instead of Default, it starts looking pretty

**Comment by benediktvaldez** [comment]
@eirikurn how does this link look for you?

http://beta.apis.is/firm/is?name=alm

**Comment by eirikurn** [comment]
That looks right.

**Comment by MiniGod** [comment]
I did some research:
Problem is that the [cache functionality][1] is not sending value of [res.charset][2]. Using [`res.type`][3] should fix the issue.

PRs are welcome @eirikurn
[1]: https://github.com/kristjanmik/apis/blob/e7351bee5fd9284ecd93aab7a8e1c13526feb77f/lib/cache.js#L24
[2]: http://expressjs.com/3x/api.html#res.charset
[3]: http://expressjs.com/3x/api.html#res.type
