### ISSUE TITLE
Create meta endpoints

### ISSUE THREAD

**Issue by benediktvaldez** [apis-is/apis#199]
So we want to create meta endpoints, partially mapped from the official github API, but to some extent manually entered info.

`/meta/maintainers` > list of official maintainers
from [/orgs/apis-is/public_members](https://api.github.com/orgs/apis-is/public_members) (only maintainers should be public members of the org)

`/meta/contributors` > list of all contributors
from [/repos/apis-is/apis/contributors](https://api.github.com/repos/apis-is/apis/contributors)

`/meta/sponsors` > list of sponsors
if sponsors have a github user/org than it would be hardcoded into the endpoint

`/meta/about` > content that goes into the about section on the documentation page (hardcoded into endpoint)

**Comment by koddsson** [comment]
Maybe we could host all that under the `/meta` route? So `/sponsors` would be `/meta/sponsors`.

**Comment by kristjanmik** [comment]
@koddsson genius. Please come back to the same continent so I can give you a big hug

**Comment by benediktvaldez** [comment]
@koddsson agree completely - first we ruled it out, but we were thinking `apis.is/apis/sponsors` which looked weird, `/meta` is much better

**Comment by benediktvaldez** [comment]
So I updated the initial comment to reflect this `meta` decision, but also added an `/about` subendpoint

**Comment by koddsson** [comment]
I started something in the `v2-meta` branch.

**Comment by benediktvaldez** [comment]
@koddsson expanded on that - experimenting with the maintainers endpoint though, was thinking instead of just returning this
```json
[
  {
    "login": "benediktvaldez",
    "avatar_url": "https://avatars.githubusercontent.com/u/1928103?v=3",
    "url": "https://api.github.com/users/benediktvaldez"
  },
  {
    "login": "koddsson",
    "avatar_url": "https://avatars.githubusercontent.com/u/318208?v=3",
    "url": "https://api.github.com/users/koddsson"
  }
]
```
I'd like to get something like this (getting the data from the `url` above)
```json
[
  {
    "user": "benediktvaldez",
    "avatar": "https://avatars.githubusercontent.com/u/1928103?v=3",
    "name": "",
    "email": "",
    "bio": ""
  },
  {
    "user": "koddsson",
    "avatar": "https://avatars.githubusercontent.com/u/318208?v=3",
    "name": "",
    "email": "",
    "bio": ""
  }
]
```
But not sure how best to do that - was trying something like this ...
```javascript
endpoint.get('/maintainers/', function(req, res, fail) {
  var options = {
    url: 'https://api.github.com/orgs/apis-is/public_members',
    headers: {
      'User-Agent': 'apis-is'
    }
  };

  request.get(options, function(err, response, body) {
    if (err) return res.json({error: err});

    var maintainers = _.map(JSON.parse(body), function(n) {
      var user = {};
      request.get({ url: n.url, headers: { 'user-agent': 'apis-is' } }, function(error, res, data) {
        if (err) return;
        user = JSON.parse(data);
      });
      var maintainer = {
        'user': n.login,
        'avatar': n.avatar_url
      };
      maintainer.name = user.name;
      maintainer.email = user.email;
      maintainer.hireable = user.hireable;
      maintainer.bio = user.bio;
      return maintainer;
    });

    return res.json(maintainers);
  });
});
```
... but the second request hasn't finished at `return res.json(maintainers)` leaving me with nothing but `user` and `avatar`

I think my approach is wrong - thoughts?

**Comment by MiniGod** [comment]
Use `async.map` instead, and move all the logic into the `request.get` callback, then `res.json` in the result callback of `async.map`.

**Comment by koddsson** [comment]
I've got something working but got hit by the github api rate limit. Will pick it up tomorrow.

**Comment by koddsson** [comment]
![screen shot 2015-03-04 at 22 03 12](https://cloud.githubusercontent.com/assets/318208/6500047/322cc55a-c2ba-11e4-8109-a88f6ba6165f.png)

Something like this? It's missing `bio` and I might have drunk to much of the `async` kool-aid so I'm gonna sober up and I'll push it tomorrow once I've had a change to refactor and clean it up a bit.

**Comment by benediktvaldez** [comment]
Looks great @koddsson - looking forward to it :smiley_cat:

**Comment by koddsson** [comment]
Added `bio` and removed `hirable`. I just pushed the async madness, I think it's a correct approach to this but I'm new to `async` so I'm not 100%. Check it out and tell me what you think :)

**Comment by kristjanmik** [comment]
Meta has been merged so I'm closing this. Create a new thread to work on updates
