### ISSUE TITLE
Sport events endpoints errors

### ISSUE THREAD

**Issue by krizziix** [apis-is/apis#202]
Both apis.is/sports/handball and http://apis.is/sports/football are giving out some errors

### Error: "error": "Could not parse the game data"

**Comment by koddsson** [comment]
Thanks for letting us know! I'll be working on this issue and will be updating this issue as I go along.

**Comment by koddsson** [comment]
I've made a pull request to quick-fix this issue (#203) that should be live once it's merged. I will then be investigating this further during this weekend to see why our tests did not catch these errors and what we can do to prevent these types of errors in the future.

**Comment by krizziix** [comment]
Awesome!

**Comment by koddsson** [comment]
The server has been updated and the sports endpoint seem to working normally again. @kristjaningi Don't hesitate to open up another issue in case there is something more that we can help you with! :tada:

**Comment by kristjaningi** [comment]
I will. Thanks for resolving the issue so quickly! @koddsson
