### ISSUE TITLE
Datastore

### ISSUE THREAD

**Issue by kristjanmik** [apis-is/apis#206]
We need some way of storing data. This issue will be updated as we figure more out.

**Comment by koddsson** [comment]
I really want this!

A couple of things that have been suggest to be and things I was thinking myself:

- A centralised database where companies can add their logos and you can always get it in various sizes and formats.
- A phone book that's free and API friendly.

**Comment by kristjanmik** [comment]
I have been taking an extensive look at the AWS infrastructure. They provide a lot of useful ways to solve our problems.

**Comment by koddsson** [comment]
Does the advania hosting setup provide some sort of hosted NoSQL like [AWSs DynamoDB](https://aws.amazon.com/dynamodb)?

I kind of don't want to run our own database and would like to use something like that or just move completely to AWS and use their database solution.

**Comment by kristjanmik** [comment]
Nope, unfortunately :/ We could host our own, but it would add some ops to the stack

**Comment by benediktvaldez** [comment]
After having used AWS extensively for the last couple of months, I'm more and more inclined to recommend moving APIs there completely.. They solve so many issues so easily, like scaling, load balancing, storage, etc. etc. etc. - cost is trivial, we could find a sponsor/sponsors willing to help us with it (I'll help with finding that if you guys want, kolibri has fx shown interest in that)..

Example setup I've been working with lately; kubernetes cluster with load balancers fronting X number of pod instances that can automatically scale up (basically runs itself).. I could show you guys live examples if we meet up when you get home @kristjanmik

**Comment by koddsson** [comment]
Yup, we use AWS pretty extensively at PV and it's really, really, really nice.

**Comment by kristjanmik** [comment]
@benediktvaldez I'm down. The problem with hosting stuff outside of Iceland is the roundtrip to scrape the data.
Iceland -> request from Iceland 10ms + 10ms both ways + source server delay  < 100ms total with response
hosted in Ireland -> request to server from Iceland 50ms one way + server requests a site in iceland 50ms + server gets data back 50ms + server sends data back to requester in Iceland 50ms over 200ms
This can get out of hand pretty quickly,  but it is a tradeoff we can look into if we do more caching

**Comment by benediktvaldez** [comment]
Yeah I think caching should solve this adequately - personally think the tradeoff is worth it..

Let's revive the APIs meetups when you get back ;)

**Comment by kristjanmik** [comment]
Yeah we have to! It is probably more fun to meet up during the summertime, last few times were so cold!
