### ISSUE TITLE
Move v1 endpoints over to v2.

### ISSUE THREAD

**Issue by koddsson** [apis-is/apis#209]
We've got a bunch that should be moved over. Here's a list:
- [ ] address (#208)
- [ ] bus
- [ ] car
- [ ] cinema
- [ ] company
- [ ] concerts
- [ ] currency
- [ ] cyclecounter
- [ ] declension
- [ ] earthquake
- [ ] flight
- [ ] golf
- [ ] hospital
- [ ] lottery (#207)
- [ ] names
- [ ] particulates
- [ ] price
- [ ] rides
- [ ] sarschool
- [ ] sports
- [ ] tv
- [ ] weather

**Comment by koddsson** [comment]
I've added the beginner friendly label to indicate that this issue is good for people new to the project looking for some way to contribute.

**Comment by alexanderbsig** [comment]
Can I read somewhere about what exactly needs to be done?
What differes V1 from V2? :smile:

**Comment by kristjanmik** [comment]
The original plan was to port all the endpoints to the new platorm. We have abandoned that plan and we are now planning on update each endpoint if needed.

**Comment by kristjanmik** [comment]
@alexanderbsig after this commit 6049ec23cd103c2fe58a75143c0876e269791de9 we have es6 support project wide!

**Comment by koddsson** [comment]
I don't think we have a notion of v1 and v2 any more since v2 has stalled.
