### ISSUE TITLE
image is null

### ISSUE THREAD

**Issue by hafsteinn** [apis-is/apis#211]
image field er alltaf http://kvikmyndir.isnull fyrir http://apis.is/cinema

**Comment by koddsson** [comment]
Thanks for filing this @hafsteinn. We'll get right on it as soon as possible. (probably later tonight).

**Comment by koddsson** [comment]
Yo @hafsteinn. I'm told by my compadres that we no longer support the `/cinema` endpoint due to kvikmyndir.is asking us to shut it down and redirect people to their own endpoint.

You can contact them [here](http://kvikmyndir.is/um-kvikmyndir/) for a API key.

Sorry :sob:

**Comment by hafsteinn** [comment]
Alrightythen, thanks for the quick replies though!

**Comment by koddsson** [comment]
We'll accept any pull request that scrapes other data source than kvikmyndir.is though! (like midi.is or smarabio.is)
