### ISSUE TITLE
Port project to io.js?

### ISSUE THREAD

**Issue by koddsson** [apis-is/apis#216]
Seems like a good play. Would there be any objections or concerns about doing this?

**Comment by kristjanmik** [comment]
You are talking about v2 right?

**Comment by koddsson** [comment]
Sure :) Although if v1 would be easy to port then maybe that too?

**Comment by kristjanmik** [comment]
I think we should only do v2 for now. Most people who pick up the project are barely familiar to nodejs and adding io.js to the mix would be confusing for now.

**Comment by koddsson** [comment]
Tr3w

**Comment by kristjanmik** [comment]
io.js is merging back into node, lets look at it when that merger is done
