### ISSUE TITLE
Calendar endpoint

### ISSUE THREAD

**Issue by koddsson** [apis-is/apis#218]
[Possible datasource](http://www.almanak.hi.is/ar/2015.html)

**Comment by MiniGod** [comment]
For holidays, we could use [Googles official holiday calendars][1].

Same source for any country basically:
[Icelandic Holidays][iceland], [USA Holidays][usa], [Norwegian Holidays][norway], etc, etc, etc

[or in `.ical` format][ical]

[1]: https://www.google.com/calendar/render?tab=mc#settings-dir_10%7Choliday
[iceland]: https://www.google.com/calendar/feeds/en.is%23holiday%40group.v.calendar.google.com/public/basic
[usa]: https://www.google.com/calendar/feeds/en.usa%23holiday%40group.v.calendar.google.com/public/basic
[norway]: https://www.google.com/calendar/feeds/en.norwegian%23holiday%40group.v.calendar.google.com/public/basic
[ical]: https://www.google.com/calendar/ical/en.is%23holiday%40group.v.calendar.google.com/public/basic

**Comment by koddsson** [comment]
Oh sweet @MiniGod

**Comment by koddsson** [comment]
I'm closing this due to the fact that people can just use the above mentioned link instead of adding this into apis and then having have to support it :grin:
