### ISSUE TITLE
Consuming other JSON data.

### ISSUE THREAD

**Issue by koddsson** [apis-is/apis#219]
Ok so I've been messing with @davidarnarsson's [boozefind](https://github.com/davidarnarsson/boozefind) and was thinking to run a cronjob on my server to scrape the data and stick into a json file and then serve that up statically.

Would we be interested in consuming that json file or would we rather run the cronjob our selves?

What do you think @MiniGod @kristjanmik @benediktvaldez?

**Comment by davidarnarsson** [comment]
This post inspired me to fix up my scraping code a little bit. I removed the dependency on CasperJS and made the implementation a little more resilient to faults. http://github.com/davidarnarsson/vinbud-scraper is the result. The resulting JSON files (one with stock information, and one without) weigh in at 2.8MB and 1.3MB.

**Comment by MiniGod** [comment]
That looks awesome @davidarnarsson!

For `v2`, we want endpoints to be able to run scrapers periodically, but as an initial implementation (or possibly for `v1`?), I see no reason to not fetch this JSON data from your server @koddsson.

**Comment by koddsson** [comment]
@davidarnarsson Sweeet! [I had a really hard time figuring out the other code in casperjs](https://twitter.com/koddsson/status/597864991727968256) so I'm glad to see this! I'm taking a look right now and have some suggestions for changes that I'll make in a PR later tonight!

**Comment by davidarnarsson** [comment]
Hah, yeah. I know the feeling. I remember being really confused when I worked with CasperJS at the time. Turns out the functions I used in Casper are easy to implement. One less dependency, one less future headache :smiley:

**Comment by koddsson** [comment]
I'm closing this since I've gotten my answer and #221 got merged!
