### ISSUE TITLE
Add endpoint for gas prices.

### ISSUE THREAD

**Issue by koddsson** [apis-is/apis#227]
![](http://i.imgur.com/6hl0t9D.png)

http://www.ob.is/eldsneytisverd/
http://www.orkan.is/eldsneytisverd/
http://www.atlantsolia.is/stodvarverd.aspx
https://www.n1.is/listaverd/
http://www.gsmbensin.is/gsmbensin_web.php

**Comment by koddsson** [comment]
Apparently @daggala is already working on this.

**Comment by koddsson** [comment]
@daggala, still working on this?

**Comment by daggala** [comment]
Yes @koddsson I am, I'm just on a vacation but I'll get back to it soon. Is there a deadline?

**Comment by koddsson** [comment]
Nope! Just checking in :sweat_smile:

**Comment by phm3** [comment]
I used some tiny snippet for that, maybe you want to port it ;)

https://gist.github.com/phm3/fd04b03bf92de8d7402c

**Comment by kristjanmik** [comment]
@phm3 neat!

**Comment by kristjanmik** [comment]
Voilà

```javascript
var x = require('x-ray')();
var _ = require('lodash');

x('http://gsmbensin.is/gsmbensin_web.php', {
  okt95: x(['.pricetable[id=okt95] tr:not(.header) td']),
  disel: x(['.pricetable[id=disel] tr:not(.header) td'])
})(function(error,data){

  function clean(n){
    return {
      station: n[0],
      location: n[1],
      price: n[2]
    }
  }

  data.okt95 = _.chunk(data.okt95,3).map(clean);
  data.disel = _.chunk(data.disel,3).map(clean);

  console.log(data);
});

/*
{
	okt95: [{
		station: 'Orkan',
		location: 'Eiðistorg',
		price: '185.50'
	}],
	disel: [{
		station: 'Orkan',
		location: 'Eiðistorg',
		price: '169.50'
	}...]
}
*/
```

**Comment by phm3** [comment]
:+1:

**Comment by Loknar** [comment]
do we agree that this has been resolved by https://github.com/apis-is/apis/pull/290 ?

http://docs.apis.is/#endpoint-petrol
