### ISSUE TITLE
Add endpoint for available parking 

### ISSUE THREAD

**Issue by koddsson** [apis-is/apis#228]
http://bilastaedasjodur.is/#bilahusin

**Comment by kristjanmik** [comment]
OMG I WANT THIS NAO!

**Comment by raldur** [comment]
Working on it - ready tonight :+1:

**Comment by koddsson** [comment]
Consider me excited @raldur!

**Comment by raldur** [comment]
https://github.com/apis-is/apis/pull/229

Kind of a rush work - I'd appreciate some feedback!

**Comment by kristjanmik** [comment]
I'm closing this down since it has been implemented. I'm working on merging in the new changes right now.
