### ISSUE TITLE
Load time

### ISSUE THREAD

**Issue by alexanderbsig** [apis-is/apis#241]
I am quite new to the field of API's and REST.

But I was thinking, sometimes our (apis.is) sources are slow or down and thus 
our endpoints unresponsive. 

Would it be a good idea to add an optional parameter to an URL  that tells how long the 
client wants to wait for a response? or is this solely the clients responsibility to handle on his side? Or maybe that makes the endpoint not restfull anymore? 

If it is not our responsibility what about having some time frame that we wait for the request (on our side) from our sources so that if the client is not thinking about it he at least will get a response lets say after 30 seconds or something.

**Comment by kristjanmik** [comment]
It is usually up to the client to set the timeout of the request, but you bring up a good point on the data reliability and responsiveness. Like you mentioned some endpoints are very slow due to the source and we haven't really tackled the problem yet. We need to improve this somehow and I guess we need more discussion on it. Thanks @alexanderbsig for bringing it up!

**Comment by koddsson** [comment]
I have been thinking about this a lot recently and have been wondering if we should start scraping the data sources at a interval and storing in cache so it can be :zap: fast when users call the endpoint. Finally we could introduce a parameter to force the endpoint to fetch a fresh batch of data if the data is really time sensitive. But for a majority of our endpoints I think time is not a huge factor.

**Comment by kristjanmik** [comment]
It might be hard for endpoints that contain query like the car endpoint. For other endpoints it would be awesome!

**Comment by koddsson** [comment]
Oh yeah, that's a good point!

**Comment by koddsson** [comment]
Now I'm wondering if we can speed anything up if the upstream server is slow. There are bound to be cache hacks but there's no way of making a server we don't control be faster. :cry:

**Comment by koddsson** [comment]
I think it's safe to say that we're not gonna solve this anytime soon.
