### ISSUE TITLE
Staðfangaskrá

### ISSUE THREAD

**Issue by grimurd** [apis-is/apis#242]
Have you considered putting up a rest endpoint for staðfangaskrá?

http://opingogn.is/dataset/stadfangaskra

**Comment by kristjanmik** [comment]
No we have not but the dataset looks good! It would be nice to make it more accessible through apis.is

**Comment by spoldman** [comment]
Just so people know, I have used this data before and it was full of errors. Like postal codes that doesn't exist. But hopefully they have fixed that. Still I think this could be a great endpoint to implement
