### ISSUE TITLE
Add endpoint for Icelandic holidays

### ISSUE THREAD

**Issue by gaui** [apis-is/apis#272]
I made a Node module that scrapes Icelandic holidays (and other important days) from [dagatal.is](http://dagatal.is). This module could be used to implement an apis.is endpoint.

https://www.npmjs.com/package/fridagar

**Comment by kristjanmik** [comment]
I really like the idea!

friday fri(frí)day(dagur) would be a funny name :P

**Comment by MiniGod** [comment]
@kristjanmik But `/calendar` would make more sense ;)

**Comment by koddsson** [comment]
I'm gonna pick this up if no one else is working on this.
