### ISSUE TITLE
Company endpoint bug

### ISSUE THREAD

**Issue by stefanhar** [apis-is/apis#286]
The the fields in the company endpoint are empty on live but work locally

/company?name=eimskip

### Steps to reproduce
GET http://apis.is/company?name=eimskip
![image](https://cloud.githubusercontent.com/assets/6640435/15045098/5163687a-12c8-11e6-9536-9dd5dcb3af57.png)

**Comment by koddsson** [comment]
This should get fixed once #287 gets merged! Thanks for the bug report! <3
