### ISSUE TITLE
Sports endpoint errors

### ISSUE THREAD

**Issue by sindris12** [apis-is/apis#288]
I was trying out the Sports API earlier and found a bug. Tried it on the server and locally. 

/apis/sports/football according to the source code should return a array of upcoming matches but at the moment it returns a array with about 50 instances of the same object

```
{
      "counter": "1",
      "date": "mán. 09. maí",
      "time": "19:00",
      "tournament": "Borgunarbikar karla",
      "location": "Vivaldivöllurinn",
      "homeTeam": "Kría",
      "awayTeam": "KB",
      "undefined": "Fram 3"
}
```

Also notices that when making API requests to the following endpoint you get outdated results
/sports/football/male-leagues/pepsi/ 

The url thats being used to fetch the data for that endpoint is the results of the league last year. 
Current url: http://www.ksi.is/mot/motalisti/urslit-stada/?MotNumer=33503
New url: http://www.ksi.is/mot/motalisti/urslit-stada/?MotNumer=35586

This is probably a error on all the specific endpoints for each division as it looks like KSI creates a new tournament each year for all divisions.

**Comment by koddsson** [comment]
Should be fixed in #293
