### ISSUE TITLE
Changes to endpoint currency/arion

### ISSUE THREAD

**Issue by gsmari** [apis-is/apis#294]
More types of currencies for endpoint currency/arion:
- SedlaGengi
- AlmenntGengi
- KortaGengi
- AirportGengi

Borgun also shows up on their website but it has a different format and result data is different from types above. Also, there is already a endpoint for borgun.

Type parameter is optional, AlmenntGengi is the default.

**Comment by koddsson** [comment]
This seems to have been fixed in #294

**Comment by MiniGod** [comment]
I assume you mean a different issue number?

**Comment by koddsson** [comment]
lol yeah, I meant #296
