### ISSUE TITLE
Give people that land a PR on master push access?

### ISSUE THREAD

**Issue by koddsson** [apis-is/apis#327]
(I got this idea from a blog post somewhere, so credit to them)

Is there any real downside to giving people push access once the land a PR? We'd still expect people to open up PRs for any non-trivial stuff but I feel like it might empower people even more to contribute, especially when the four contributors we have now are busy with other stuff.

What do you think?

**Comment by kristjanmik** [comment]
I think it is a good idea if people have contributed something of value
