### ISSUE TITLE
Some ssn are not found in the company API even though they are present at RSK website

### ISSUE THREAD

**Issue by simottar** [apis-is/apis#349]
Hi guys,

There seems to be a bug in the Company part of apis.is

I know you are taking the data by scraping the RSK website.
But there are some SSN that the api is not finding even when they are on the RSK website:

For example http://apis.is/company?socialnumber=5902697199 is not returning anything even if it works at RSK website: https://www.rsk.is/fyrirtaekjaskra/leit/kennitala/5902697199

Anyways I also want to thank you for creating apis.is, it is a great api! :+1: 

### Steps to reproduce

1. Go to http://apis.is/company?socialnumber=5902697199
    This only returns an empty result
2. https://www.rsk.is/fyrirtaekjaskra/leit/kennitala/5902697199
    This works at the RSK website.

**Comment by Loknar** [comment]
Hi @simottar, I am not an apis maintainer, but I've contributed to this project in the past.

I encourage you (and anyone who's interested really) to try running this project locally to check further what's going wrong in cases like this one.

```
git clone git@github.com:apis-is/apis.git
cd apis
npm install
node index.js
```

I thought I could maybe see what's going wrong in your case, but I actually found out this social security number works when running apis locally ... so it's possible the apis IP address has been blocked by rsk.is for some reason (might be by some automated process if apis at some point bombarded them with requests, and if so it'll likely be blocked temporarily, however this should be checked by one of the maintainers if they have the time).

As can be seen here https://github.com/apis-is/apis/blob/master/endpoints/company/index.js#L58 the result is saved in cache for 86400 seconds (24 hours), it seems that the error detection (which should end up responding with a 500 error and the message `www.rsk.is refuses to respond or give back data` is not good enough and therefore an empty response was saved to cache.

If a maintainer could access the machine the backend is running on (or proxy through its IP address) and try running the following
```
curl https://www.rsk.is/fyrirtaekjaskra/leit/kennitala/5902697199
```
to see if we're currently blocked that would be nice.

**Comment by Loknar** [comment]
As a future feature to prevent things like this from happening we could look into somehow making sure we don't spam pages we're scraping for information with some kind of rate limit implementation and endpoint specific rate-limit settings. :suspect:

**Comment by MiniGod** [comment]
I can curl those pages with no problem from the server, but also see that apis.is is responding correctly for that ssn now. It has been in the cache for approximately 3 hours.

@Loknar @simottar If you find another ssn that this happens to, please comment and I will try to look at it asap.

Being rate-limited has definitely been an issue before, and still is, and is definitely something we want to solve.
