### ISSUE TITLE
Add a endpoint for Anthology, collection of Icelandic literary

### ISSUE THREAD

**Issue by olafur164** [apis-is/apis#377]
Hi, i was working on an app for a school project recently where i was scraping http://visna.net and i thought it would be nice to be able to get icelandic poems and verses in JSON format
Websites ideas to scrape: 
- http://bragi.info
- http://visna.net
- http://ljod.is

the endpoint(s) could be set up like this.
/anthology
/anthology/poems
/anthology/verses

**Comment by koddsson** [comment]
This sounds neat, thanks for opening the issue 🎉 ! I have a couple of questions, if that's cool.

>the endpoint(s) could be set up like this.
/anthology
/anthology/poems
/anthology/verses

What would these endpoint return and what parameters would they take in? Is `/anthology/poems` returning all poems we can scrape in a paginated result?

How are you thinking about the data structure of the poems? Initially I'm thinking something like this, but I'm not sure if I'm missing some metadata:

```json
{
    "title": "foo",
    "body": "bar",
    "published": 2017
}
```

What's the difference between poems and verses?

**Comment by olafur164** [comment]
Great that you like it.

ye to get further into it, i'm not sure what params they might take in, maybe things like id, author and published?

Regarding the data structure i thought something like this which i used in my app when scraping http://visna.net but it might be better to structure it a bit better

```
{
     id: "522",
    title: "Á Njáluslóðum.",
    text: "Á Hlíðarenda var heljar drift,
    en hjónabandið var allt í báli.
    Því Hallgerður var homma gyft,
    og hann var alltaf að ríða Njáli.",
    author: "Höfundur:  Sálmaskáldið.",
    published: ""
}
```

The difference between poems and verses, how i think of it is that Poems are Ljóð and that verses are more like lausavísur (i. fyndnar vísur, klámvísur og eitthvað svoleiðis)

**Comment by koddsson** [comment]
Cool! Here's what I'm thinking and please do note that this is just my own opinion and I'm not benevolent dictator here 😸 

While this could be a good endpoint for people to use the data doesn't seem "scientific" enough to me to warrant adding it to apis.is at this stage. We are really low on resources to add endpoints and maintain the project right now. Previously we've had endpoints that give you the air quality in Reykjavík and seismic activity that developers can use to build apps with and with poems I can mostly see it being a poem reading app and not much more.

That being said, if you or someone else want's to pick this up and work on this and make a PR we will accept it with thanks but right now I don't think we'll put this on the roadmap 💖

**Comment by olafur164** [comment]
Ye i was actually thinking of doing this and making a PR, just wanted to find out what you guys thought of that first 😃

**Comment by olafur164** [comment]
and yea i understand completely that the data doesn't seem scientific enough :smiley so maybe not something that should be a priority, i just thought it would be neat and also maybe help preserving Icelandic literature

**Comment by koddsson** [comment]
Awesome! I can't see why not; we have plenty of endpoints right now 😄 

If I can make a suggestion about the API for this endpoint. I'm thinking about something like this:

```
/poems               <- returns a paginated list of poems
/poems/:id          <- returns a single poem
/poems/random <- returns a random poem
```

and the data structure could be something like this:

```
GET /poems
{
  "results": [...],
  "pagination": {
    "current": 1,
    "next": 2,
    "previous": null,
    "total": 1597
}
```

I also think that starting with one datasource would make sense instead of trying to all the data sources at once and running into issues with pagination. But it's of course your call 😄
