### ISSUE TITLE
Use our own eslint

### ISSUE THREAD

**Issue by koddsson** [apis-is/apis#379]
The airbnb eslint config seems geared towards a react web app and that's not what we're about. We should replace it with our own. Copy pasting the airbnb one seems reasonable to me as a starting point.

**Comment by MiniGod** [comment]
I think there are a lot of really nice rules in airbnb, and getting updates from them would be good, imo.
Our own config package can extend from airbnb's config, then disable the rules that do not fit us?

**Comment by koddsson** [comment]
For sure the updates are good but they also come with stuff like peerdependencies on some eslint-react package and the list of stuff we are disabling is kind of growing with each update.

Maybe there's a similar preset for node that we can get because the updates are really nice like you mentioned.
