### ISSUE TITLE
The tests fail from day to day

### ISSUE THREAD

**Issue by koddsson** [apis-is/apis#416]
There is probably something in the currency endpoint (since the tests seem to fail there) that is time sensitive since the tests will fail the day after the mock data being regenerated.

Ref: https://github.com/apis-is/apis/pull/415#issuecomment-351969403

**Comment by koddsson** [comment]
I will be testing this and trying to fix tomorrow.

**Comment by MiniGod** [comment]
This was fixed in #438.
