### ISSUE TITLE
Aircraft endpoint

### ISSUE THREAD

**Issue by valentinoli** [apis-is/apis#430]
I have implemented a new endpoint for data about registered aircraft at the [Icelandic Transport Authority](https://www.samgongustofa.is/flug/loftfor/loftfaraskra). Would you be interested in integrating this `/aircraft` endpoint into the current endpoint collection? The implementation is highly inspired by `/ship`.

**Comment by koddsson** [comment]
We'd totally be interested in integrating it! 😄

**Comment by valentinoli** [comment]
That's great! How should we proceed?

**Comment by koddsson** [comment]
Making a PR to this repo with the code would be a good start. I can help moving the PR forward and help land the feature.

**Comment by valentinoli** [comment]
When I attempt to make a PR, the button for creating it is disabled.

![capture](https://user-images.githubusercontent.com/23453691/35767899-12103542-08ec-11e8-99d0-0c76293c5638.JPG)

**Comment by valentinoli** [comment]
Nevermind that! Learning something new here. Pull request successfully submitted #431
