### ISSUE TITLE
Endpoint to return opening times of swimming pools in iceland

### ISSUE THREAD

**Issue by kristjanmik** [apis-is/apis#44]
[sundlaugar.is](www.sundlaugar.is) is a horribad website and this one can almost not be found [http://reykjavik.is/desktopdefault.aspx/tabid-3697/6079_view-1520/](http://reykjavik.is/desktopdefault.aspx/tabid-3697/6079_view-1520/). I will probably implement this endpoint in the next couple of weeks, do you know any other data source where this data can be scraped from?

**Comment by koddsson** [comment]
Maybe the owner of [laug.is](https://laug.is/) would be so kind of gracing us with his/her data? :grin:
