### ISSUE TITLE
Icelandic holidays and other dates

### ISSUE THREAD

**Issue by JonGretar** [apis-is/apis#445]
Discussion of the creation of a API endpoint for Icelandic holidays.

As I have seen too many questions on the existence of an API for listing Icelandic holidays then this issue should be the starting point of such a resource. For best results this should not do any scraping but do it's own calculation of these dates.

Amongst key things that need to be discussed:
- [ ] Definition of the queries.
- [ ] Definition of the results.
- [ ] iCal support?
- [ ] Should other dates that have names be included (bónda-/konudagur) and how should those be defined so not to confuse with legal holidays.
- [ ] Are there nice open source holiday calculators out there that we could base on.
- [ ] Other types of related date based data that would be nice.

Other Projects: 
 - [moment-holiday](https://github.com/kodie/moment-holiday)
 - [date-holidays](https://github.com/commenthol/date-holidays) (Includes Iceland(unverified))
 - [HolidaysCalendar](https://github.com/carrer/HolidaysCalendar)

Resources:
 - [Vísindavefur: Hverjir eru lögbundnir frídagar okkar Íslendinga?](https://www.visindavefur.is/svar.php?id=1692)
 - [Wikipedia: Lögbundnir frídagar á Íslandi](https://is.wikipedia.org/wiki/L%C3%B6gbundnir_fr%C3%ADdagar_%C3%A1_%C3%8Dslandi)

**Comment by JonGretar** [comment]
Jumped the gun possibly. 
Undocumented API exists https://github.com/apis-is/apis/tree/master/endpoints/calendar that uses https://github.com/gaui/fridagar-node

Is everyone happy with it? Does it need improvement or shall we just document it and close the issue?

**Comment by koddsson** [comment]
>Is everyone happy with it? Does it need improvement or shall we just document it and close the issue?

I think documenting it and closing would be great ✨
