### ISSUE TITLE
Advania Cloud shutting down - need new hosting provider

### ISSUE THREAD

**Issue by MiniGod** [apis-is/apis#469]
For the last few years Advania has been sponsoring a server to us in Advania Open Cloud. We are grateful for the last few years with them, but unfortunately __Advania Open Cloud is shutting down__ and we have until the __6th of December 2018__ to find a new provider.

Minimal requirements _(please comment below if something is missing, and I'll add it to the list)_:
* Hosted in Iceland (latency to source data)
* 2GB RAM
* Free (sponsored)

**Comment by kristjanmik** [comment]
Preferably free, since the project has no revenue stream

**Comment by sse87** [comment]
I have contacted Advania (Rekstrarlausnir) and they are willing to support the project. Who can I send further details and will manage the migration?

**Comment by kristjanmik** [comment]
@sse87 Thank you for the offer. Advania reached out immediately after @MiniGod created the issue.

**Comment by kristjanmik** [comment]
Advania has given us access to their private cloud. Fantastic work on their end! We will start migrating in the next few weeks.
