### ISSUE TITLE
raven@2.4.2 alert: no DSN provided, error reporting disabled

### ISSUE THREAD

**Issue by sse87** [apis-is/apis#470]
I can see it's when `SENTRY_URL` is `undefined` or a valid sentry dsn string. It's not a bug just noise when running dev and test.
I thought it was in used by CircleCI but I can see it's also displayed there:
![image](https://user-images.githubusercontent.com/273553/46196069-90634100-c2f5-11e8-9570-4c1f93dc8dba.png)

Is it just outdated code so it's OK to remove it or at least hide it by not run raven install when it's `undefined`?

**Comment by MiniGod** [comment]
We use this in production only, so checking if it is set is probably a good idea!

**Comment by MiniGod** [comment]
Fixed in #471
