### ISSUE TITLE
Horse endpoint is not responding data

### ISSUE THREAD

**Issue by christianMurschall** [apis-is/apis#473]
If I make a request to the horse endpoint e.g. `http://apis.is/horses?id=IS1987187700` I get the error 

> {"error":"www.worldfengur.com refuses to respond or give back data"}

### Steps to reproduce

Is it a issue with:
 - the service running on http://apis.is? Yes
 - running the service locally? Yes
I installed it locally and it looks, that worldfengur responds with status code 500. 
 - documentation? Not at all.

**Comment by baroninn** [comment]
The problem is with Wordfengur, not apis
if you visit their worldfengur page they report that the freezone search is down due to maintenance.

> Due to maintenance work on WorldFengur, a freezone horse search can not be offered at this time. We apologise for any inconvenience this may cause.

**Comment by Loknar** [comment]
I contacted Worldfengur via email yesterday evening asking the following:

> Sæl/Sæll,
> 
> Ég sé að freezone horse uppflettisíðan hjá ykkur hefur verið niðri í einhvern tíma núna. Stendur til að opna hana aftur í framtíðinni?
> 
> Mbk,
> Sveinn Flóki

I got a reply this morning:

> Sæll Sveinn Flóki
> 
> Nei, síðan verður ekki opnuð aftur.

:(
