### ISSUE TITLE
CORS error on weather endpoint

### ISSUE THREAD

**Issue by saevarom** [apis-is/apis#479]
Describe the issue you are having here.

### Steps to reproduce

* Call the weather endpoint with the provided example in a browser console. You will get a CORS error.

```
$.ajax({
  'url': 'http://apis.is/weather/observations/en',
  'type': 'GET',
  'dataType': 'json',
  'data': {'stations': '1,422', 'time': '1h', 'anytime': '0'},
  'success': function(response) {
    console.log(response);
  }
});
```

The resulting error:

<img width="511" alt="screenshot 2019-01-03 09 35 36" src="https://user-images.githubusercontent.com/143557/50631061-eec63e00-0f3a-11e9-9653-3359a4479b0d.png">

**Comment by MiniGod** [comment]
Interesting! It looks like this happens because you're using `http` instead of `https`. For the last month or so, we've been redirecting `http` to `https` with a 301, but forgot to add the CORS headers to the 301 response.

Thanks for pointing this out!

Let me know if `https` works for you.

**Comment by saevarom** [comment]
Ah, didn't think of trying https, just copied the example in the docs!
HTTPS works, thanks!
