### ISSUE TITLE
Cloud coverage endpoint

### ISSUE THREAD

**Issue by jeremybarbet** [apis-is/apis#488]
Hi guys!

I was looking at the `/weather` endpoint and I was wondering where to find a cloud coverage dataset that I could use along with Mapbox.

I checked data from DWD, NOAA, and other meteorological stations but without luck. Since I'm looking for something really specific to Iceland, you might know where I could get the most accurate data, and if it could be part of apis-is

Cheers!

**Comment by Loknar** [comment]
Veðurstofa Íslands has a cloud forecast map https://www.vedur.is/vedur/spar/skyjahula/ but this forecast is as far as I know only available as a set of pictures ... you could of course "parse the pixels" to some more usable data, but could take some work ...  :sweat_smile:

Observed cloud status in pecific locations is available here http://brunnur.vedur.is/athuganir/skyjahula/gogn/2019-03/skyjahula_2019-03-24_15.html and here http://brunnur.vedur.is/athuganir/skyjahula/gogn/2019-03/skyjahula_2019-03-24_15.txt

Veðurstofa Íslands provides public access to all kinds of data here http://brunnur.vedur.is/ .. for example here are lightnings that have struck over Iceland for the past 24hours http://brunnur.vedur.is/athuganir/eldingar/elding.txt

**Comment by jeremybarbet** [comment]
Yeah it would definitely be a bit of work to extract data from each image, I'm not sure I want to start doing this 😂

Even though, I was looking for open data from Veðurstofa and http://brunnur.vedur.is is great, thanks for that.

I'll keep looking for the clouds solution

**Comment by Loknar** [comment]
I have a feeling you can achieve a suitable solution by using cloud images from here

http://brunnur.vedur.is/kort/harmonie/2019/03/27/18/harmonie_island_lcc_mcc_tcc.html

with the mapbox image overlay functionality

https://docs.mapbox.com/mapbox-gl-js/example/image-on-a-map/

you just need to figure out what coordinates to use to suitably place the cloud image on the mapbox

(urls to the images themselves are fairly consistent it seems, here's one for example http://brunnur.vedur.is/kort/harmonie/2019/03/27/18/harmonie_island_lcc_mcc_tcc_2019032718_000.jpg)

edit:

man, getting these coordinates right is hard tho ... https://jsfiddle.net/sv1floki/c7pdenbL/1/

**Comment by jeremybarbet** [comment]
Thanks for the link and example!

Yeah and even if you get the coordinates rights, you might have a bit of offset between both Iceland map.

There is also this guy that is interesting: http://brunnur.vedur.is/kort/harmonie/2019/03/27/18/harmonie_island_tcc_lcc_mcc_hcc.html

As you said in the first reply, I think parsing the jpg images and getting data out of it sounds interesting, but probably not easy to do
