### ISSUE TITLE
Get request error

### ISSUE THREAD

**Issue by sigurdurhaukur** [apis-is/apis#496]
Don't know if you noticed but when someone clicks on the link in the title bar for example: /bus/realtime you get a error
{"error":"Something is wrong with the data provided from the data source"}
### Steps to reproduce

it is a issue with:
 - the service running on http://apis.is

**Comment by kristjanmik** [comment]
Hi @sigurdurhaukur.

Thank you for raising this issue!

Strætó has been going through some drastic changes that we have unfortunately not been unable to backport into the API. The endpoint is, therefore, discontinued.
